#!/bin/bash

#cp -rf ./cmd ../tgfaka_ok/
#cp -rf ./conf ../tgfaka_ok/
#cp -rf ./internal ../tgfaka_ok/
#cp -rf ./static ../tgfaka_ok/
cp -rf ./templates ../tgfaka_ok/
#cp -rf ./README.md ../tgfaka_ok/
#cp -rf ./Dockerfile ../tgfaka_ok/
cp -rf ./docker-compose.yml ../tgfaka_ok/