#!/bin/bash
echo "0"
exit
echo "1"

#删除数据库文件升级
rm -rf ./tgfaka/tmp/* && mv tgfaka_zip_ok.zip ./tgfaka/tmp/ 
cd ./tgfaka/tmp 
unzip -o tgfaka_zip_ok.zip && rm -rf .env 
cp -rf ./* ../
cd .. 
docker-compose down && rm -rf .env/.db
bash _rebuild 
pwd


#保留现存数据升级
rm -rf ./tgfaka/tmp/* && mv tgfaka_zip_ok.zip ./tgfaka/tmp/ 
cd ./tgfaka/tmp 
unzip -o tgfaka_zip_ok.zip && rm -rf .env 
cp -rf ./* ../
cd .. 
bash _rebuild
pwd