version: "3.3"
services:
  tgfaka:
    image:  annona/tgfaka:latest
    container_name: "tgfaka"
    restart: always
    # build: .
    # command: /app/main --port 8082
    volumes:
      - ./.env:/app/.env
      - ./upload:/app/upload
      - ./templates:/app/templates
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8082:8082"
