version: "3.3"
services:
  tgfaka:
    image:  annona/annona_tgfaka:latest
    container_name: tgfaka
    restart: always
    # build: .
    # command: /app/main --port 8082
    volumes:
      - ./conf:/app/conf
      - ./upload:/app/upload
      - ./templates:/app/templates
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8082:8082"
